server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_Students
    username: ENC(o3f+nYG0FjdWbLFwuWe+Gw==)
    password: ENC(lnfR76jiZOQWrvMOJeFxJA==)
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

jasypt:
  encryptor:
    password: {$JASYPT_ENCRYPTOR_PASSWORD:}
